# Generated by Django 3.1.1 on 2020-10-16 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EAB_DataStoreSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='tbd', max_length=100, verbose_name='Data Store System name')),
                ('datastoresystem_approved', models.CharField(choices=[('RRCS_APPROVED_CHANNEL', 'Approved Channel'), ('RRCS_NOT_APPROVED_CHANNEL', 'Not Approved as a Channel for Export Controlled data')], default='RRCS_OTHER', max_length=30, verbose_name='Data store system channel status')),
            ],
            options={
                'verbose_name': 'Data Store System',
                'verbose_name_plural': 'Data Store System',
            },
        ),
        migrations.CreateModel(
            name='EAB_DataStoreSystemArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='tbd', max_length=100, verbose_name='Area name')),
                ('export_classification_PL9009c', models.BooleanField(default=False, verbose_name='Intended to contain PL9009.c')),
                ('export_classification_EU_dualuse', models.BooleanField(default=False, verbose_name='Intended to contain EU Dual Use')),
                ('export_classification_US_NLR', models.BooleanField(default=False, verbose_name='Intended to contain US NLR (no license required)')),
                ('dss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dss_areas', to='cetus3pur.eab_datastoresystem')),
            ],
            options={
                'verbose_name': 'Data storage system Area',
                'verbose_name_plural': 'Data storage system Areas',
            },
        ),
        migrations.CreateModel(
            name='ThirdParty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_entity_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('ad_group_name', models.CharField(default='AD group todo', max_length=50, verbose_name='AD Group Name')),
            ],
            options={
                'verbose_name': '3P Business',
                'verbose_name_plural': '3P Businesses',
            },
        ),
        migrations.CreateModel(
            name='ThirdPartyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='First name')),
                ('familyname', models.CharField(max_length=50, verbose_name='Family name')),
                ('employee_id', models.CharField(max_length=20, verbose_name='3P Employee ID')),
                ('userac_name', models.CharField(max_length=10, verbose_name='User account name')),
                ('userac_expirydate', models.DateField(verbose_name='Expiry date')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cetus3pur.thirdparty')),
            ],
            options={
                'verbose_name': '3P User',
                'verbose_name_plural': '3P Users',
            },
        ),
        migrations.CreateModel(
            name='EAB_Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of request', verbose_name='Date')),
                ('reqstr_userid', models.CharField(help_text='User account of person making the request', max_length=10, verbose_name='Requester User ID')),
                ('data_owner_userid', models.CharField(max_length=10, verbose_name='Data Owner User ID')),
                ('ipecr', models.IntegerField(blank=True, default='TBD', verbose_name='IPECR #')),
                ('data_store_system', models.ForeignKey(help_text='The IT System that holds the data', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_store_system', to='cetus3pur.eab_datastoresystem')),
                ('data_store_system_area', models.ForeignKey(help_text='A reposotory, subfolder, or other part of the IT System, which is to be exported (shared with a 3rd party)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_store_system_area', to='cetus3pur.eab_datastoresystemarea')),
                ('tp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_party', to='cetus3pur.thirdparty', verbose_name='Third Party')),
            ],
            options={
                'verbose_name': 'EAB Request',
                'verbose_name_plural': 'EAB Requests',
            },
        ),
        migrations.CreateModel(
            name='EAB_Approval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date of Review')),
                ('approver_userid', models.CharField(max_length=10, verbose_name='Approver User ID')),
                ('decision', models.CharField(choices=[('NYR', 'Not Yet Reviewed'), ('APP', 'Approved'), ('REJ', 'Rejected'), ('PEN', 'Pending')], max_length=3, verbose_name='Decision')),
                ('ecm_comment', models.CharField(max_length=512, verbose_name='ECM comment')),
                ('ipm_comment', models.CharField(max_length=512, verbose_name='IP Manager comment')),
                ('IT_comment', models.CharField(max_length=512, verbose_name='IT Comment')),
                ('request', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cetus3pur.eab_request')),
            ],
            options={
                'verbose_name': 'EAB Approval',
                'verbose_name_plural': 'EAB Approvals',
            },
        ),
    ]
