# Generated by Django 3.1.1 on 2020-10-16 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cetus3pur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eab_request',
            name='ipecr',
            field=models.IntegerField(blank=True, default=0, verbose_name='IPECR #'),
        ),
    ]
