# Generated by Django 3.1.1 on 2020-10-11 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cetus3pur', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RRResponsibleManager',
        ),
        migrations.AddField(
            model_name='eab_request',
            name='data_store_system_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_store_system_area', to='cetus3pur.eab_datastoresystemarea'),
        ),
    ]
