# Generated by Django 3.1.1 on 2020-09-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cetus3pur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirdpartyuser',
            name='userac_expirydate',
            field=models.DateField(verbose_name='Expiry date'),
        ),
    ]
