# Generated by Django 3.1.1 on 2020-10-11 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cetus3pur', '0002_auto_20201011_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eab_request',
            name='data_store',
        ),
        migrations.RemoveField(
            model_name='eab_request',
            name='data_store_export_claim',
        ),
    ]
