# Generated by Django 3.1.1 on 2020-10-16 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cetus3pur', '0002_auto_20201016_2324'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eab_request',
            unique_together={('tp', 'data_store_system', 'data_store_system_area')},
        ),
    ]
