# Generated by Django 3.1.1 on 2020-10-17 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cetus3pur', '0003_auto_20201016_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eab_request',
            name='data_owner_userid',
            field=models.CharField(help_text='User ID of the person who owns this data store', max_length=10, verbose_name='Data Owner User ID'),
        ),
        migrations.AlterField(
            model_name='eab_request',
            name='date',
            field=models.DateField(help_text='Date of this EAB request', verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='eab_request',
            name='ipecr',
            field=models.IntegerField(blank=True, default=0, help_text='A six digit number, or use 0 if unsure', verbose_name='IPECR #'),
        ),
        migrations.AlterField(
            model_name='eab_request',
            name='reqstr_userid',
            field=models.CharField(help_text='User ID of person making the request', max_length=10, verbose_name='Requester User ID'),
        ),
        migrations.AlterField(
            model_name='eab_request',
            name='tp',
            field=models.ForeignKey(help_text='Name and location must be correct', on_delete=django.db.models.deletion.CASCADE, related_name='third_party', to='cetus3pur.thirdparty', verbose_name='Third Party'),
        ),
    ]
