# Generated by Django 3.1.1 on 2020-10-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cetus3pur', '0004_auto_20201017_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='eab_request',
            name='request_locked',
            field=models.BooleanField(default=False, help_text='programmtic field used to indicate ready for review, can not be changed', verbose_name='Request Locked'),
        ),
    ]
