# Generated by Django 3.1.1 on 2020-10-24 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cetus3pur', '0005_eab_request_request_locked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eab_request',
            name='request_locked',
        ),
        migrations.CreateModel(
            name='EAB_IT_Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assigned', models.DateField(verbose_name='Date action assigned')),
                ('date_completed', models.DateField(verbose_name='Date action completed')),
                ('IT_executor_userid', models.CharField(max_length=10, verbose_name='IT executor user ID')),
                ('completed', models.BooleanField(default=False, verbose_name='Action completed')),
                ('approval', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cetus3pur.eab_approval')),
            ],
            options={
                'verbose_name': 'EAB IT Action',
                'verbose_name_plural': 'EAB IT Actions',
            },
        ),
    ]
