# Generated by Django 3.1.1 on 2020-09-15 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cetus3pur', '0006_eab_approval_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eab_request',
            name='data_owner_userid',
            field=models.CharField(max_length=10, verbose_name='Data Owner User ID'),
        ),
        migrations.AlterField(
            model_name='eab_request',
            name='data_store',
            field=models.CharField(max_length=256, verbose_name='Date Store'),
        ),
        migrations.AlterField(
            model_name='eab_request',
            name='data_store_export_claim',
            field=models.CharField(max_length=512, verbose_name='Export status of Data Store'),
        ),
        migrations.AlterField(
            model_name='eab_request',
            name='ipecr',
            field=models.IntegerField(verbose_name='IPECR #'),
        ),
        migrations.AlterField(
            model_name='eab_request',
            name='reqstr_userid',
            field=models.CharField(max_length=10, verbose_name='Requester User ID'),
        ),
    ]
