# Generated by Django 3.1.1 on 2020-10-24 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cetus3pur', '0007_auto_20201024_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eab_it_action',
            name='IT_executor_userid',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='IT executor user ID'),
        ),
        migrations.AlterField(
            model_name='eab_it_action',
            name='date_completed',
            field=models.DateField(blank=True, null=True, verbose_name='Date action completed'),
        ),
    ]
