# Generated by Django 3.1.1 on 2020-09-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cetus3pur', '0007_auto_20200915_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eab_approval',
            name='IT_comment',
            field=models.CharField(max_length=512, verbose_name='IT Comment'),
        ),
        migrations.AlterField(
            model_name='eab_approval',
            name='approver_userid',
            field=models.CharField(max_length=10, verbose_name='Approver User ID'),
        ),
        migrations.AlterField(
            model_name='eab_approval',
            name='decision',
            field=models.CharField(choices=[('APP', 'Approved'), ('REJ', 'Rejected'), ('PEN', 'Pending')], max_length=3, verbose_name='Decision'),
        ),
        migrations.AlterField(
            model_name='eab_approval',
            name='ecm_comment',
            field=models.CharField(max_length=512, verbose_name='ECM comment'),
        ),
        migrations.AlterField(
            model_name='eab_approval',
            name='ipm_comment',
            field=models.CharField(max_length=512, verbose_name='IP Manager comment'),
        ),
    ]
