# Generated by Django 3.1.1 on 2020-09-15 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cetus3pur', '0008_auto_20200915_2320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eab_approval',
            options={'verbose_name': 'EAB Approval', 'verbose_name_plural': 'EAB Approvals'},
        ),
        migrations.AlterModelOptions(
            name='eab_request',
            options={'verbose_name': 'EAB Request', 'verbose_name_plural': 'EAB Requests'},
        ),
    ]
