# Generated by Django 3.1.1 on 2020-10-25 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cetus3pur', '0010_eab_it_action_id_proxy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eab_it_action',
            name='id_proxy',
        ),
    ]
