# Generated by Django 3.1.1 on 2020-09-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cetus3pur', '0010_auto_20200915_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eab_approval',
            name='decision',
            field=models.CharField(choices=[('NYR', 'Not Yet Reviewed'), ('APP', 'Approved'), ('REJ', 'Rejected'), ('PEN', 'Pending')], max_length=3, verbose_name='Decision'),
        ),
    ]
