# Generated by Django 3.1.1 on 2020-09-26 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cetus3pur', '0011_auto_20200919_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='EAB_DataStoreSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datastoresystem', models.CharField(choices=[('RRCS_INTEGRITY', 'Integrity'), ('RRCS_ARTISAN', 'Artisan'), ('RRCS_DOORS', 'Controls DOORS'), ('RRGAD_DOORS', 'R-R Winyard/Doxford DOORS'), ('RRCS_NAS', 'Controls Network Folder'), ('RRCS_CINCOM', 'CINCOM'), ('RRCS_TFS', 'TFS'), ('RRCS_OTHER', 'Other')], default='RRCS_OTHER', max_length=20, verbose_name='Data store system')),
                ('data_store_system_other_specify', models.CharField(default='todo', max_length=256)),
            ],
            options={
                'verbose_name': 'Data Store System',
                'verbose_name_plural': 'Data Store System',
            },
        ),
        migrations.AlterField(
            model_name='eab_approval',
            name='date',
            field=models.DateField(verbose_name='Date of Review'),
        ),
        migrations.AlterField(
            model_name='eab_request',
            name='data_store',
            field=models.CharField(max_length=256, verbose_name='Date Store Area to be shared'),
        ),
        migrations.AlterField(
            model_name='eab_request',
            name='date',
            field=models.DateField(verbose_name='Date of Request'),
        ),
        migrations.AlterField(
            model_name='eab_request',
            name='tp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_party', to='cetus3pur.thirdparty'),
        ),
        migrations.AlterField(
            model_name='rrresponsiblemanager',
            name='user_ac',
            field=models.CharField(default='<null>', max_length=10, verbose_name='User account'),
        ),
        migrations.AlterField(
            model_name='thirdpartyuser',
            name='employee_id',
            field=models.CharField(max_length=20, verbose_name='3P Employee ID'),
        ),
        migrations.AlterField(
            model_name='thirdpartyuser',
            name='familyname',
            field=models.CharField(max_length=50, verbose_name='Family name'),
        ),
        migrations.AlterField(
            model_name='thirdpartyuser',
            name='firstname',
            field=models.CharField(max_length=50, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='thirdpartyuser',
            name='userac_name',
            field=models.CharField(max_length=10, verbose_name='User account name'),
        ),
        migrations.AddField(
            model_name='eab_request',
            name='data_store_system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_store_system', to='cetus3pur.eab_datastoresystem'),
        ),
    ]
