# Generated by Django 3.1.1 on 2020-09-26 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cetus3pur', '0012_auto_20200926_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdparty',
            name='ad_group_name',
            field=models.CharField(default='AD group todo', max_length=50, verbose_name='AD Group Name'),
        ),
        migrations.AlterField(
            model_name='eab_request',
            name='tp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_party', to='cetus3pur.thirdparty', verbose_name='Third Party'),
        ),
    ]
